volumes:
    flexed:
        external: true
    pg-admin-data:
        external: true
services:
    pg-admin-new:
        image: dpage/pgadmin4
        volumes:
            - pg-admin-data:/var/lib/pgadmin
        ports:
            - 8082:80
        environment:
            PGADMIN_DEFAULT_EMAIL: noahmaurer12@gmail.com
            PGADMIN_DEFAULT_PASSWORD: flexed
            PGADMIN_DISABLE_POSTFIX: 1
    api:
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        environment:
            DATABASE_URL: postgresql://example_user:secret@db/flexed
            WAIT_HOSTS: db:5432
            PORT: 8000
            SIGNING_KEY: LFHHF777828723487KJDH77GJHGH4564654GJHGJHG8877KJGKJHKJHKJHSSNNFIIEW548R6T7T8T99I
        ports:
            - "8000:8000"
        volumes:
            - ./api:/app
    db:
        image: postgres:14.5-bullseye
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: example_user
            POSTGRES_DB: flexed
        ports:
            - "15432:5432"
        volumes:
            - flexed:/var/lib/postgresql/data
    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        volumes:
            - ./flexed:/app
        ports:
            - "3000:3000"
        environment:
            HOST_OS: ${OS}
            NODE_ENV: development
            HOST: "0.0.0.0"
            PUBLIC_URL: http://localhost:3000
            REACT_APP_FLEXED_SERVICE_API_HOST: http://localhost:8000
